[[redirects]]
	from = "/openjdk-cannot-be-opened-because-the-developer-cannot-be-verified-adb-brew/"
	to = "https://raquo.net/2020/03/openjdk-cannot-be-opened-because-the-developer-cannot-be-verified-adb-brew/"
	force = true

[[redirects]]
	from = "/react-typescript-vscode-unable-to-resolve-module/"
	to = "https://raquo.net/2020/02/react-typescript-vscode-unable-to-resolve-module/"
	force = true

[[redirects]]
	from = "/ffmpeg-exited-with-code-1-homebridge-axis-camera/"
	to = "https://raquo.net/2020/01/ffmpeg-exited-with-code-1-homebridge-axis-camera/"
	force = true

[[redirects]]
	from = "/xcodebuild-error-could-not-resolve-package-dependencies/"
	to = "https://raquo.net/2020/01/xcodebuild-error-could-not-resolve-package-dependencies/"
	force = true

[[redirects]]
	from = "/left-side-of-comma-operator-is-unused-and-has-no-side-effects/"
	to = "https://raquo.net/2018/11/left-side-of-comma-operator-is-unused-and-has-no-side-effects/"
	force = true
